### ISSUE TITLE
Can't render sidebar in the pad

### ISSUE THREAD

**Issue by nupamore** [chancethecoder/multipad#5]
The pad can destroy itself, but `renderSidebar()` is within `main.js` only.
I don't know to solve this problem.

**Comment by chancethecoder** [comment]
2 options

1. trigger `renderSidebar()` when DOM is loaded and reload if instances are modified by main process

2. handle event at renderer process and pass it to `main.js` by calling webcontents.executeJavaScript
http://electron.atom.io/docs/api/web-contents/#contentsexecutejavascriptcode-usergesture-callback

**Comment by chancethecoder** [comment]
option 2:
I don't know if it works.
